### PR TITLE
Set up CIBuildWheels for pip install ; cmake cleanup

### PR DESCRIPTION
**Pull request by alecjacobson**
# `pip install libigl` 🥳

- New Github Actions workflow to use cibuildwheels to prepare .whl files that can be uploaded to pypi.org at https://pypi.org/project/libigl/ (send me your pypi username if you'd like to be added as a maintainer)
  - includes mac arm build 🚀
  - many other python × os builds
  - runs tests on all (except mac arm; not supported by github actions for now)
- Simplified and cleaned up cmake
  - rename flags to be clearer that they control downloading data
  - use `FetchContent*` in modern cmake
  - don't use cmake for python tests
  - numpyeigen is still a fragile cmake include; I _think_ this is due to how numpyeigen's cmake is set up, but perhaps could be improved on our end
  - deleted unnecessary files
- `setup.py`
  -  reads in `MAX_JOBS` to control parallelism. For now the github actions are using `2` but I [think](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) it could be `2` on windows/linux and `3` on mac. (Note: I tried `8` and this created a lot of issues with builds stalling on github actions. I think it was out of memory issues but not sure.)
  - now reads in version from `igl/_version.py` which also sets up `igl.__version__` in the module. (there're long discussions [here](https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package) and I went with one of the more straightforward recommendations).
- `tests/test_basic.py`
  - cibuildwheels runs the tests _out of source_, so I removed all the hard-coded paths and made it read the test data directory from argument. 
  
  
I've had good feedback so far that linux, mac and windows users can install libigl easily from pip. I propose we merge this, keep pypi up to date and remove the conda distribution.

### CODE REVIEW

**Comment by alecjacobson** [comment]
Oh, and when this is merged. It would make sense to do a github release for 2.4.1 as well.

**Comment by alecjacobson** [comment]
Currently 3.11 is not supported due to old pybind11 inherited from old numpyeigen:new_numpy_hacks_stable . I'm trying now to see if the newest numpyeigen will just solve this. If it does, I'll include that in this PR. If it doesn't I think we just need to say 3.11 is not supported until we figure out our relationship with numpyeigen.

**Comment by alecjacobson** [comment]
Doesn't seem like that Azure error is a real issue. I think we can turn off this Azure thing as cibuildwheels action makes it obsolete.

**Comment by alecjacobson** [comment]
3.11 works. Just needed to update numpyeigen, now included in this PR.

**Comment by alecjacobson** [comment]
Fixes #159 
Fixes #158 
Fixes #45

**Comment by paddyroddy** [comment]
Great work!

**Pull request merged**
